FROM mcr.microsoft.com/dotnet/sdk:latest

WORKDIR /workspace/

RUN dotnet dev-certs https --trust

# docker build -f Dockerfile.dev  -t dotnet-dev-image .
# docker run -dti --mount type=bind,source=$(pwd)/../..,target=/workspace --name dotnet-dev-container dotnet-dev-image
