FROM rust:latest

WORKDIR /workspace/

RUN apt update
RUN apt install -y lldb
RUN rustup component add rustfmt

# docker build -f Dockerfile.dev  -t rust-dev-image .
# docker run -dti --mount type=bind,source=$(pwd)/../..,target=/workspace --name rust-dev-container rust-dev-image
